#!/bin/sh

TELEGRAM_API_TOKEN=your_api_token
TELEGRAM_CHAT_ID=your_chat_id

telegram_notify() {
	curl "https://api.telegram.org/bot$TELEGRAM_API_TOKEN/sendMessage" \
		--data-urlencode "chat_id=$TELEGRAM_CHAT_ID" \
		--data-urlencode "text=$1" \
		--silent --output /dev/null
}

ERR=$(/opt/baka/baka 2>&1 >/dev/null)
RC=$?
if [ $RC != 0 ]; then
	telegram_notify "$(printf "💔 Daily backup RC=%d:\\n%s" $RC "$ERR")"
else
	telegram_notify "$(printf "💚 Daily backup RC=%d" $RC)"
fi
